// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:hermes_dart/hermes_dart.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  HermesABIArrayOrError Function(ffi.Pointer<HermesABIRuntime>, ffi.Size)
>()
external HermesABIArrayOrError hermes_array_create(
  ffi.Pointer<HermesABIRuntime> rt,
  int length,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<HermesABIRuntime>, HermesABIArray)>()
external int hermes_array_get_length(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIArray arr,
);

@ffi.Native<
  HermesABIValueOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIArray,
    ffi.Size,
  )
>()
external HermesABIValueOrError hermes_array_value_get_at_index(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIArray arr,
  int index,
);

@ffi.Native<
  HermesABIVoidOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIArray,
    ffi.Size,
    HermesABIValue,
  )
>()
external HermesABIVoidOrError hermes_array_value_set_at_index(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIArray arr,
  int index,
  HermesABIValue value,
);

@ffi.Native<
  HermesABIArrayBufferOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    HermesABIMutableBufferRelease,
  )
>()
external HermesABIArrayBufferOrError
hermes_arraybuffer_create_from_external_data(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Void> user_data,
  HermesABIMutableBufferRelease release_cb,
);

@ffi.Native<
  HermesABIUint8PtrOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIArrayBuffer,
  )
>()
external HermesABIUint8PtrOrError hermes_arraybuffer_get_data(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIArrayBuffer ab,
);

@ffi.Native<
  HermesABISizeTOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIArrayBuffer,
  )
>()
external HermesABISizeTOrError hermes_arraybuffer_get_size(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIArrayBuffer ab,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<HermesABIRuntime>, HermesABIBigInt)
>()
external int hermes_bigint_as_int64(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIBigInt bi,
);

@ffi.Native<
  HermesABIBigInt Function(ffi.Pointer<HermesABIRuntime>, HermesABIBigInt)
>()
external HermesABIBigInt hermes_bigint_clone(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIBigInt bi,
);

@ffi.Native<
  HermesABIBigIntOrError Function(ffi.Pointer<HermesABIRuntime>, ffi.Int64)
>()
external HermesABIBigIntOrError hermes_bigint_create_from_int64(
  ffi.Pointer<HermesABIRuntime> rt,
  int value,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<HermesABIRuntime>, HermesABIBigInt)>()
external bool hermes_bigint_is_int64(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIBigInt bi,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIBigInt,
    HermesABIBigInt,
  )
>()
external bool hermes_bigint_strict_equals(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIBigInt a,
  HermesABIBigInt b,
);

@ffi.Native<
  HermesABIStringOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIBigInt,
    ffi.Int,
  )
>()
external HermesABIStringOrError hermes_bigint_to_string(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIBigInt bi,
  int radix,
);

@ffi.Native<
  HermesABIStringOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Char>,
  )
>()
external HermesABIStringOrError hermes_create_string_from_utf8(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Char> str,
);

@ffi.Native<
  HermesABIValue Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
  )
>()
external HermesABIValue hermes_evaluate_bytecode(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Char> source_url,
);

@ffi.Native<
  HermesABIValue Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
  )
>()
external HermesABIValue hermes_evaluate_javascript(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> script,
  int script_len,
  ffi.Pointer<ffi.Char> source_url,
);

@ffi.Native<
  HermesABIValue Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIFunction,
    HermesABIValue,
    ffi.Pointer<HermesABIValue>,
    ffi.Size,
  )
>()
external HermesABIValue hermes_function_call(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIFunction fn,
  HermesABIValue js_this,
  ffi.Pointer<HermesABIValue> args,
  int arg_count,
);

@ffi.Native<
  HermesABIValue Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIFunction,
    ffi.Pointer<HermesABIValue>,
    ffi.Size,
  )
>()
external HermesABIValue hermes_function_call_as_constructor(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIFunction fn,
  ffi.Pointer<HermesABIValue> args,
  int arg_count,
);

@ffi.Native<
  HermesABIFunctionOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIPropNameID,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Void>,
    HermesABIHostFunctionCall,
    HermesABIHostFunctionRelease,
  )
>()
external HermesABIFunctionOrError hermes_function_create_from_host(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIPropNameID name,
  int length,
  ffi.Pointer<ffi.Void> user_data,
  HermesABIHostFunctionCall call_cb,
  HermesABIHostFunctionRelease release_cb,
);

@ffi.Native<
  HermesABIBoolOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIFunction,
  )
>()
external HermesABIBoolOrError hermes_instance_of(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIFunction ctor,
);

@ffi.Native<
  HermesABIObject Function(ffi.Pointer<HermesABIRuntime>, HermesABIObject)
>()
external HermesABIObject hermes_object_clone(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<HermesABIObjectOrError Function(ffi.Pointer<HermesABIRuntime>)>()
external HermesABIObjectOrError hermes_object_create(
  ffi.Pointer<HermesABIRuntime> rt,
);

@ffi.Native<
  HermesABIObjectOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Void>,
    HermesABIHostObjectGet,
    HermesABIHostObjectSet,
    HermesABIHostObjectGetOwnKeys,
    HermesABIHostObjectRelease,
  )
>()
external HermesABIObjectOrError hermes_object_create_from_host_object(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Void> user_data,
  HermesABIHostObjectGet get_cb,
  HermesABIHostObjectSet set_cb,
  HermesABIHostObjectGetOwnKeys get_own_keys_cb,
  HermesABIHostObjectRelease release_cb,
);

@ffi.Native<
  HermesABIValueOrError Function(ffi.Pointer<HermesABIRuntime>, ffi.Uint64)
>()
external HermesABIValueOrError hermes_object_from_id(
  ffi.Pointer<HermesABIRuntime> rt,
  int id,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<HermesABIRuntime>, HermesABIObject)
>()
external ffi.Pointer<ffi.Void> hermes_object_get_native_state_data(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<
  HermesABIValue Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIPropNameID,
  )
>()
external HermesABIValue hermes_object_get_property_from_propnameid(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIPropNameID name,
);

@ffi.Native<
  HermesABIValue Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIValue,
  )
>()
external HermesABIValue hermes_object_get_property_from_value(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIValue key,
);

@ffi.Native<
  HermesABIArrayOrError Function(ffi.Pointer<HermesABIRuntime>, HermesABIObject)
>()
external HermesABIArrayOrError hermes_object_get_property_names(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<
  HermesABIBoolOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIPropNameID,
  )
>()
external HermesABIBoolOrError hermes_object_has_property_from_propnameid(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIPropNameID name,
);

@ffi.Native<
  HermesABIBoolOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIValue,
  )
>()
external HermesABIBoolOrError hermes_object_has_property_from_value(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIValue key,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<HermesABIRuntime>, HermesABIObject)>()
external bool hermes_object_is_array(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<HermesABIRuntime>, HermesABIObject)>()
external bool hermes_object_is_arraybuffer(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<HermesABIRuntime>, HermesABIObject)>()
external bool hermes_object_is_function(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<
  HermesABIVoidOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    ffi.Pointer<ffi.Void>,
    HermesABINativeStateRelease,
  )
>()
external HermesABIVoidOrError hermes_object_set_native_state(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  ffi.Pointer<ffi.Void> user_data,
  HermesABINativeStateRelease release_cb,
);

@ffi.Native<
  HermesABIVoidOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIPropNameID,
    HermesABIValue,
  )
>()
external HermesABIVoidOrError hermes_object_set_property_from_propnameid(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIPropNameID name,
  HermesABIValue value,
);

@ffi.Native<
  HermesABIVoidOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIValue,
    HermesABIValue,
  )
>()
external HermesABIVoidOrError hermes_object_set_property_from_value(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
  HermesABIValue key,
  HermesABIValue value,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
    HermesABIObject,
  )
>()
external bool hermes_object_strict_equals(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject a,
  HermesABIObject b,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<HermesABIManagedPointer>)>()
external void hermes_pointer_release(
  ffi.Pointer<HermesABIManagedPointer> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<HermesABIManagedPointer>)>()
external void hermes_pointer_release_safe(
  ffi.Pointer<HermesABIManagedPointer> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<HermesABIPreparedJavaScript>)>()
external void hermes_preparedjavascript_release(
  ffi.Pointer<HermesABIPreparedJavaScript> prepared,
);

@ffi.Native<
  HermesABIPropNameID Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIPropNameID,
  )
>()
external HermesABIPropNameID hermes_propnameid_clone(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIPropNameID name,
);

@ffi.Native<
  HermesABIPropNameIDOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIString,
  )
>()
external HermesABIPropNameIDOrError hermes_propnameid_create_from_string(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIString str,
);

@ffi.Native<
  HermesABIPropNameIDOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABISymbol,
  )
>()
external HermesABIPropNameIDOrError hermes_propnameid_create_from_symbol(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABISymbol sym,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIPropNameID,
    HermesABIPropNameID,
  )
>()
external bool hermes_propnameid_equals(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIPropNameID a,
  HermesABIPropNameID b,
);

@ffi.Native<
  HermesABIStringData Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIPropNameID,
  )
>()
external HermesABIStringData hermes_propnameid_get_data(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIPropNameID prop,
);

@ffi.Native<
  ffi.Pointer<HermesABIPropNameIDList> Function(
    ffi.Pointer<HermesABIPropNameID>,
    ffi.Size,
  )
>()
external ffi.Pointer<HermesABIPropNameIDList> hermes_propnameid_list_create(
  ffi.Pointer<HermesABIPropNameID> props,
  int size,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIPropNameID,
  )
>()
external ffi.Pointer<ffi.Char> hermes_propnameid_to_utf8(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIPropNameID name,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<HermesABIManagedPointer>,
  )
>()
external void hermes_register_pointer(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<HermesABIManagedPointer> ptr,
);

@ffi.Native<ffi.Pointer<HermesABIRuntime> Function(HermesABIRuntimeConfig)>()
external ffi.Pointer<HermesABIRuntime> hermes_runtime_create(
  HermesABIRuntimeConfig config,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<HermesABIRuntime>, ffi.Int)>()
external bool hermes_runtime_drain_microtasks(
  ffi.Pointer<HermesABIRuntime> rt,
  int max_microtasks_hint,
);

@ffi.Native<HermesABIValue Function(ffi.Pointer<HermesABIRuntime>)>()
external HermesABIValue hermes_runtime_get_and_clear_js_error_value(
  ffi.Pointer<HermesABIRuntime> rt,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<HermesABIRuntime>)>()
external ffi.Pointer<ffi.Char>
hermes_runtime_get_and_clear_native_exception_message(
  ffi.Pointer<HermesABIRuntime> rt,
);

@ffi.Native<HermesABIObject Function(ffi.Pointer<HermesABIRuntime>)>()
external HermesABIObject hermes_runtime_get_global_object(
  ffi.Pointer<HermesABIRuntime> rt,
);

@ffi.Native<
  HermesABIPreparedJavaScriptOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
  )
>()
external HermesABIPreparedJavaScriptOrError
hermes_runtime_prepared_javascript_create(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> utf8_source,
  int source_length,
  ffi.Pointer<ffi.Char> source_url,
);

@ffi.Native<
  HermesABIValueOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<HermesABIPreparedJavaScript>,
  )
>()
external HermesABIValueOrError hermes_runtime_prepared_javascript_evaluate(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<HermesABIPreparedJavaScript> prepared,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<HermesABIRuntime>)>()
external void hermes_runtime_release(
  ffi.Pointer<HermesABIRuntime> rt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<HermesABIRuntime>)>()
external void hermes_runtime_release_from_finalizer(
  ffi.Pointer<HermesABIRuntime> rt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<HermesABIRuntime>, HermesABIValue)>()
external void hermes_runtime_set_js_error_value(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIValue error_value,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<HermesABIRuntime>, ffi.Pointer<ffi.Char>)
>()
external void hermes_runtime_set_native_exception_message(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Char> message,
);

@ffi.Native<
  HermesABIString Function(ffi.Pointer<HermesABIRuntime>, HermesABIString)
>()
external HermesABIString hermes_string_clone(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIString str,
);

@ffi.Native<
  HermesABIStringData Function(ffi.Pointer<HermesABIRuntime>, HermesABIString)
>()
external HermesABIStringData hermes_string_get_data(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIString str,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIString,
    HermesABIString,
  )
>()
external bool hermes_string_strict_equals(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIString a,
  HermesABIString b,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<HermesABIRuntime>, HermesABIString)
>()
external ffi.Pointer<ffi.Char> hermes_string_to_utf8(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIString str,
);

@ffi.Native<
  HermesABISymbol Function(ffi.Pointer<HermesABIRuntime>, HermesABISymbol)
>()
external HermesABISymbol hermes_symbol_clone(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABISymbol sym,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABISymbol,
    HermesABISymbol,
  )
>()
external bool hermes_symbol_strict_equals(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABISymbol a,
  HermesABISymbol b,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<HermesABIRuntime>, HermesABISymbol)
>()
external ffi.Pointer<ffi.Char> hermes_symbol_to_utf8(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABISymbol sym,
);

@ffi.Native<
  HermesABIValueOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external HermesABIValueOrError hermes_value_create_from_json_utf8(
  ffi.Pointer<HermesABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> json_bytes,
  int length,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Pointer<HermesABIRuntime>, HermesABIValue)
>()
external int hermes_value_get_unique_id(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIValue val,
);

@ffi.Native<
  HermesABIWeakObjectOrError Function(
    ffi.Pointer<HermesABIRuntime>,
    HermesABIObject,
  )
>()
external HermesABIWeakObjectOrError hermes_weak_object_create(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIObject obj,
);

@ffi.Native<
  HermesABIValue Function(ffi.Pointer<HermesABIRuntime>, HermesABIWeakObject)
>()
external HermesABIValue hermes_weak_object_lock(
  ffi.Pointer<HermesABIRuntime> rt,
  HermesABIWeakObject wo,
);

final class HermesABIArray extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIArray> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIArray>()..ref.pointer = pointer;
}

final class HermesABIArrayBuffer extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIArrayBuffer> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIArrayBuffer>()..ref.pointer = pointer;
}

final class HermesABIArrayBufferOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIArrayBufferOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<HermesABIArrayBufferOrError>()
        ..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIArrayOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIArrayOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<HermesABIArrayOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIBigInt extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIBigInt> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIBigInt>()..ref.pointer = pointer;
}

final class HermesABIBigIntOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIBigIntOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<HermesABIBigIntOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIBoolOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int bool_or_error;

  static ffi.Pointer<HermesABIBoolOrError> $allocate(
    ffi.Allocator $allocator, {
    required int bool_or_error,
  }) => $allocator<HermesABIBoolOrError>()..ref.bool_or_error = bool_or_error;
}

enum HermesABIErrorCode {
  HermesABIErrorCodeNativeException(0),
  HermesABIErrorCodeJSError(1)
  ;

  final int value;
  const HermesABIErrorCode(this.value);

  static HermesABIErrorCode fromValue(int value) => switch (value) {
    0 => HermesABIErrorCodeNativeException,
    1 => HermesABIErrorCodeJSError,
    _ => throw ArgumentError('Unknown value for HermesABIErrorCode: $value'),
  };
}

final class HermesABIFunction extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIFunction> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIFunction>()..ref.pointer = pointer;
}

final class HermesABIFunctionOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIFunctionOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<HermesABIFunctionOrError>()..ref.ptr_or_error = ptr_or_error;
}

typedef HermesABIHostFunctionCall =
    ffi.Pointer<ffi.NativeFunction<HermesABIHostFunctionCallFunction>>;
typedef HermesABIHostFunctionCallFunction =
    HermesABIValueOrError Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<HermesABIRuntime> rt,
      ffi.Pointer<HermesABIValue> this_arg,
      ffi.Pointer<HermesABIValue> args,
      ffi.Size arg_count,
    );
typedef DartHermesABIHostFunctionCallFunction =
    HermesABIValueOrError Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<HermesABIRuntime> rt,
      ffi.Pointer<HermesABIValue> this_arg,
      ffi.Pointer<HermesABIValue> args,
      int arg_count,
    );
typedef HermesABIHostFunctionRelease =
    ffi.Pointer<ffi.NativeFunction<HermesABIHostFunctionReleaseFunction>>;
typedef HermesABIHostFunctionReleaseFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data);
typedef DartHermesABIHostFunctionReleaseFunction =
    void Function(ffi.Pointer<ffi.Void> user_data);
typedef HermesABIHostObjectGet =
    ffi.Pointer<ffi.NativeFunction<HermesABIHostObjectGetFunction>>;
typedef HermesABIHostObjectGetFunction =
    HermesABIValueOrError Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<HermesABIRuntime> rt,
      HermesABIPropNameID name,
    );
typedef HermesABIHostObjectGetOwnKeys =
    ffi.Pointer<ffi.NativeFunction<HermesABIHostObjectGetOwnKeysFunction>>;
typedef HermesABIHostObjectGetOwnKeysFunction =
    HermesABIPropNameIDListPtrOrError Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<HermesABIRuntime> rt,
    );
typedef HermesABIHostObjectRelease =
    ffi.Pointer<ffi.NativeFunction<HermesABIHostObjectReleaseFunction>>;
typedef HermesABIHostObjectReleaseFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data);
typedef DartHermesABIHostObjectReleaseFunction =
    void Function(ffi.Pointer<ffi.Void> user_data);
typedef HermesABIHostObjectSet =
    ffi.Pointer<ffi.NativeFunction<HermesABIHostObjectSetFunction>>;
typedef HermesABIHostObjectSetFunction =
    HermesABIVoidOrError Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<HermesABIRuntime> rt,
      HermesABIPropNameID name,
      ffi.Pointer<HermesABIValue> value,
    );

final class HermesABIManagedPointer extends ffi.Opaque {}

typedef HermesABIMutableBufferRelease =
    ffi.Pointer<ffi.NativeFunction<HermesABIMutableBufferReleaseFunction>>;
typedef HermesABIMutableBufferReleaseFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data);
typedef DartHermesABIMutableBufferReleaseFunction =
    void Function(ffi.Pointer<ffi.Void> user_data);
typedef HermesABINativeStateRelease =
    ffi.Pointer<ffi.NativeFunction<HermesABINativeStateReleaseFunction>>;
typedef HermesABINativeStateReleaseFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data);
typedef DartHermesABINativeStateReleaseFunction =
    void Function(ffi.Pointer<ffi.Void> user_data);

final class HermesABIObject extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIObject> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIObject>()..ref.pointer = pointer;
}

final class HermesABIObjectOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIObjectOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<HermesABIObjectOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIPreparedJavaScript extends ffi.Opaque {}

final class HermesABIPreparedJavaScriptOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIPreparedJavaScriptOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<HermesABIPreparedJavaScriptOrError>()
        ..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIPropNameID extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIPropNameID> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIPropNameID>()..ref.pointer = pointer;
}

final class HermesABIPropNameIDList extends ffi.Opaque {}

final class HermesABIPropNameIDListPtrOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIPropNameIDListPtrOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<HermesABIPropNameIDListPtrOrError>()
        ..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIPropNameIDOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIPropNameIDOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<HermesABIPropNameIDOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class HermesABIRuntime extends ffi.Opaque {}

final class HermesABIRuntimeConfig extends ffi.Struct {
  @ffi.Bool()
  external bool enable_eval;

  @ffi.Bool()
  external bool es6_proxy;

  @ffi.Bool()
  external bool enable_generator;

  @ffi.Bool()
  external bool enable_async_generators;

  @ffi.Bool()
  external bool es6_block_scoping;

  @ffi.Bool()
  external bool intl;

  @ffi.Bool()
  external bool microtask_queue;

  @ffi.Int32()
  external int compilation_mode;

  @ffi.Uint32()
  external int bytecode_warmup_percent;

  @ffi.Bool()
  external bool optimized_eval;

  @ffi.Bool()
  external bool enable_hermes_internal;

  @ffi.Bool()
  external bool enable_hermes_internal_test_methods;

  @ffi.Bool()
  external bool randomize_memory_layout;

  static ffi.Pointer<HermesABIRuntimeConfig> $allocate(
    ffi.Allocator $allocator, {
    required bool enable_eval,
    required bool es6_proxy,
    required bool enable_generator,
    required bool enable_async_generators,
    required bool es6_block_scoping,
    required bool intl,
    required bool microtask_queue,
    required int compilation_mode,
    required int bytecode_warmup_percent,
    required bool optimized_eval,
    required bool enable_hermes_internal,
    required bool enable_hermes_internal_test_methods,
    required bool randomize_memory_layout,
  }) => $allocator<HermesABIRuntimeConfig>()
    ..ref.enable_eval = enable_eval
    ..ref.es6_proxy = es6_proxy
    ..ref.enable_generator = enable_generator
    ..ref.enable_async_generators = enable_async_generators
    ..ref.es6_block_scoping = es6_block_scoping
    ..ref.intl = intl
    ..ref.microtask_queue = microtask_queue
    ..ref.compilation_mode = compilation_mode
    ..ref.bytecode_warmup_percent = bytecode_warmup_percent
    ..ref.optimized_eval = optimized_eval
    ..ref.enable_hermes_internal = enable_hermes_internal
    ..ref.enable_hermes_internal_test_methods =
        enable_hermes_internal_test_methods
    ..ref.randomize_memory_layout = randomize_memory_layout;
}

final class HermesABISizeTOrError extends ffi.Struct {
  @ffi.Bool()
  external bool is_error;

  external UnnamedUnion$2 data;
}

final class HermesABIString extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIString> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIString>()..ref.pointer = pointer;
}

final class HermesABIStringData extends ffi.Struct {
  @ffi.Bool()
  external bool is_ascii;

  external ffi.Pointer<ffi.Void> data;

  @ffi.Size()
  external int length;

  static ffi.Pointer<HermesABIStringData> $allocate(
    ffi.Allocator $allocator, {
    required bool is_ascii,
    required ffi.Pointer<ffi.Void> data,
    required int length,
  }) => $allocator<HermesABIStringData>()
    ..ref.is_ascii = is_ascii
    ..ref.data = data
    ..ref.length = length;
}

final class HermesABIStringOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIStringOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<HermesABIStringOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class HermesABISymbol extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABISymbol> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABISymbol>()..ref.pointer = pointer;
}

final class HermesABIUint8PtrOrError extends ffi.Struct {
  @ffi.Bool()
  external bool is_error;

  external UnnamedUnion$1 data;
}

final class HermesABIValue extends ffi.Struct {
  @ffi.Int()
  external int kindAsInt;

  HermesABIValueKind get kind => HermesABIValueKind.fromValue(kindAsInt);
  set kind(HermesABIValueKind value) => kindAsInt = value.value;

  external UnnamedUnion data;
}

enum HermesABIValueKind {
  HermesABIValueKindUndefined(0),
  HermesABIValueKindNull(1),
  HermesABIValueKindBoolean(2),
  HermesABIValueKindError(3),
  HermesABIValueKindNumber(4),
  HermesABIValueKindSymbol(-2147483643),
  HermesABIValueKindBigInt(-2147483642),
  HermesABIValueKindString(-2147483641),
  HermesABIValueKindObject(-2147483639)
  ;

  final int value;
  const HermesABIValueKind(this.value);

  static HermesABIValueKind fromValue(int value) => switch (value) {
    0 => HermesABIValueKindUndefined,
    1 => HermesABIValueKindNull,
    2 => HermesABIValueKindBoolean,
    3 => HermesABIValueKindError,
    4 => HermesABIValueKindNumber,
    -2147483643 => HermesABIValueKindSymbol,
    -2147483642 => HermesABIValueKindBigInt,
    -2147483641 => HermesABIValueKindString,
    -2147483639 => HermesABIValueKindObject,
    _ => throw ArgumentError('Unknown value for HermesABIValueKind: $value'),
  };
}

final class HermesABIValueOrError extends ffi.Struct {
  external HermesABIValue value;
}

final class HermesABIVoidOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int void_or_error;

  static ffi.Pointer<HermesABIVoidOrError> $allocate(
    ffi.Allocator $allocator, {
    required int void_or_error,
  }) => $allocator<HermesABIVoidOrError>()..ref.void_or_error = void_or_error;
}

final class HermesABIWeakObject extends ffi.Struct {
  external ffi.Pointer<HermesABIManagedPointer> pointer;

  static ffi.Pointer<HermesABIWeakObject> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<HermesABIManagedPointer> pointer,
  }) => $allocator<HermesABIWeakObject>()..ref.pointer = pointer;
}

final class HermesABIWeakObjectOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<HermesABIWeakObjectOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<HermesABIWeakObjectOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class UnnamedUnion extends ffi.Union {
  @ffi.Bool()
  external bool boolean;

  @ffi.Double()
  external double number;

  external ffi.Pointer<HermesABIManagedPointer> pointer;

  @ffi.UnsignedInt()
  external int errorAsInt;

  HermesABIErrorCode get error => HermesABIErrorCode.fromValue(errorAsInt);
  set error(HermesABIErrorCode value) => errorAsInt = value.value;
}

final class UnnamedUnion$1 extends ffi.Union {
  external ffi.Pointer<ffi.Uint8> val;

  @ffi.Uint16()
  external int error;
}

final class UnnamedUnion$2 extends ffi.Union {
  @ffi.Size()
  external int val;

  @ffi.Uint16()
  external int error;
}
